version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '${PG_PORT}:${PG_PORT}'
    restart: unless-stopped
volumes:
  db:
    external: true
